// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGroup(arg1, arg2) {
  return window['go']['main']['App']['AddGroup'](arg1, arg2);
}

export function AddServiceToGroup(arg1, arg2) {
  return window['go']['main']['App']['AddServiceToGroup'](arg1, arg2);
}

export function CreateService(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['CreateService'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteService(arg1) {
  return window['go']['main']['App']['DeleteService'](arg1);
}

export function EditService(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['EditService'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function Exit() {
  return window['go']['main']['App']['Exit']();
}

export function FetchLogsForService(arg1) {
  return window['go']['main']['App']['FetchLogsForService'](arg1);
}

export function FetchServiceFile(arg1) {
  return window['go']['main']['App']['FetchServiceFile'](arg1);
}

export function FetchServiceGroup() {
  return window['go']['main']['App']['FetchServiceGroup']();
}

export function FetchServices() {
  return window['go']['main']['App']['FetchServices']();
}

export function FetchServicesOfAGroup(arg1) {
  return window['go']['main']['App']['FetchServicesOfAGroup'](arg1);
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}
