// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGroup(arg1:string,arg2:string):Promise<void>;

export function AddServiceToGroup(arg1:string,arg2:string):Promise<void>;

export function CreateService(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string):Promise<void>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteService(arg1:string):Promise<void>;

export function EditService(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string):Promise<void>;

export function Exit():Promise<void>;

export function FetchServiceFile(arg1:string):Promise<string>;

export function FetchServiceGroup():Promise<string>;

export function FetchServices():Promise<string>;

export function FetchServicesOfAGroup(arg1:string):Promise<string>;

export function Minimize():Promise<void>;

export function RestartService(arg1:string):Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;
